/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as RecognitionAndApprovalsRouteImport } from './routes/recognition-and-approvals'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const RecognitionAndApprovalsRoute = RecognitionAndApprovalsRouteImport.update({
  id: '/recognition-and-approvals',
  path: '/recognition-and-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/institutions': typeof InstitutionsRoute
  '/recognition-and-approvals': typeof RecognitionAndApprovalsRoute
  '/research': typeof ResearchRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/institutions': typeof InstitutionsRoute
  '/recognition-and-approvals': typeof RecognitionAndApprovalsRoute
  '/research': typeof ResearchRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/institutions': typeof InstitutionsRoute
  '/recognition-and-approvals': typeof RecognitionAndApprovalsRoute
  '/research': typeof ResearchRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/academics'
    | '/admissions'
    | '/institutions'
    | '/recognition-and-approvals'
    | '/research'
    | '/courses/$slug'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/academics'
    | '/admissions'
    | '/institutions'
    | '/recognition-and-approvals'
    | '/research'
    | '/courses/$slug'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/academics'
    | '/admissions'
    | '/institutions'
    | '/recognition-and-approvals'
    | '/research'
    | '/courses/$slug'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  InstitutionsRoute: typeof InstitutionsRoute
  RecognitionAndApprovalsRoute: typeof RecognitionAndApprovalsRoute
  ResearchRoute: typeof ResearchRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recognition-and-approvals': {
      id: '/recognition-and-approvals'
      path: '/recognition-and-approvals'
      fullPath: '/recognition-and-approvals'
      preLoaderRoute: typeof RecognitionAndApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  InstitutionsRoute: InstitutionsRoute,
  RecognitionAndApprovalsRoute: RecognitionAndApprovalsRoute,
  ResearchRoute: ResearchRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
